# test config mushra page, no waveform, 3 conditions, no looping


testname: MUSHRA without looping and waveform
testId: mushra_noloop_nowav
bufferSize: 4096
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:

    - type: consent
      content: "This is a MUSHRA listening test designed to investigate participants' perception of and ability to identify AI-generated singers. You will listen to a series of short audio samples sung by either AI or human performers. For each sample, you will provide two ratings:
                Human-likeness – how much the voice sounds like a human singer (0 = clearly AI, 100 = clearly human)
                Quality and appeal – how much you would enjoy hearing the track in a concert (0 = poor quality / not enjoyable, 100 = excellent / very enjoyable)
                The test will take approximately 10–15 minutes to complete. Your responses will be anonymised and securely stored. Participation is voluntary, and you may choose not to answer any question or exit the test at any time.
                
                Before starting the test, please adjust the volume starting from 0 to a comfortable level."


    - type: languageFamiliarity
      id: lang_fam
      name: Language Familiarity
      content: "Please rate your familiarity with the following languages (0 = not familiar, 100 = very familiar)."
    

    - type: mushra
      id: trial2
      name: MUSHRA test 
      content: test description
      showWaveform: false
      enableLooping: false 
      sliderCount: 2 
      reference: configs/resources/audio/Smbdytolv_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/Smbdytolv_crab.wav
          C2: configs/resources/audio/Smbdytolv_mj.wav
          C3: configs/resources/audio/Smbdytolv_audit.wav
          C4: configs/resources/audio/Smbdytolv_CD.wav
          C5: configs/resources/audio/Smbdytolv_r.wav
    

    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: false
      enableLooping: false 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav

    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: false
      enableLooping: false 
      #sliderCount: 2 
      reference: configs/resources/audio/39_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/39_AI_kim.wav
          C2: configs/resources/audio/39_AI_ace.wav

    

    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: false
      enableLooping: false 
      reference: configs/resources/audio/Watame.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/JP_suno.wav
          C2: configs/resources/audio/39_suno.wav
          C3: configs/resources/audio/mono_c3.wav

    
  

    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: false
      enableLooping: false 
      sliderCount: 2 
      reference: configs/resources/audio/TianHou_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/TianHou_justin.wav
          C2: configs/resources/audio/TianHou_boi.wav
          C3: configs/resources/audio/TianHou_xzhq.wav
          C4: configs/resources/audio/TianHou_david.wav

    

    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: false
      enableLooping: false 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav

    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: false
      enableLooping: false 
      sliderCount: 2 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav

    

    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: false
      enableLooping: false 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav

    - type: mushra
      id: trial2
      name: Mono Trial
      content: Cantonese test 1
      showWaveform: false
      enableLooping: false 
      sliderCount: 2 
      reference: configs/resources/audio/1_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/1_AImodel.wav
          #C2: configs/resources/audio/mono_c2.wav
          #C3: configs/resources/audio/mono_c3.wav

    

    - type: mushra
      id: trial2
      name: Mono Trial
      content: Cantonese test 2
      showWaveform: false
      enableLooping: false 
      reference: configs/resources/audio/IN_K.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/Mandarin_suno.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav


    - type: finish
      name: Thank you
      content: Thank you for attending
      popupContent: Your results were sent. Goodbye and have a nice day
      showResults: true
      writeResults: true
