# test config mushra page, no waveform, 3 conditions, no looping


testname: MUSHRA without looping and waveform
testId: mushra_noloop_nowav
bufferSize: 4096
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:

    - type: consent
      content: "This is a MUSHRA listening test designed to investigate participants' perception of and ability to identify AI-generated singers. You will listen to a series of short audio samples sung by either AI or human performers. For each sample, you will provide two ratings:
                Human-likeness – how much the voice sounds like a human singer (0 = clearly AI, 100 = clearly human)
                Quality and appeal – how much you would enjoy hearing the track in a concert (0 = poor quality / not enjoyable, 100 = excellent / very enjoyable)
                The test will take approximately 15-20 minutes to complete. Your responses will be anonymised and securely stored. Participation is voluntary, and you may choose not to answer any question or exit the test at any time.
                
                Before starting the test, please adjust the volume starting from 0 to a comfortable level. Please complete this test independently without consulting others or using online resources, so that your responses reflect your own personal opinion. 
                
                If you have any questions, please contact me at ttc515@york.ac.uk"


    - type: languageFamiliarity
      id: lang_fam
      name: Language Familiarity
      content: "Please rate your familiarity with the following languages (0 = not familiar, 100 = very familiar)."

    
    

    - type: gender
      id: gender
      name: Gender
      content: Please select your gender from the list below.


    

    - type: mushra
      id: english_test_1
      name: English test 1
      content: "For each language, you will complete two tests. Test 1 will involve the same song across conditions, while Test 2 will involve different songs. You may listen to the reference track first, the reference track of all tests will be human."
      showWaveform: false
      enableLooping: false 
      sliderCount: 2 
      reference: configs/resources/audio/Smbdytolv_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/normalised_Smbdytolv_crab.wav #AI
          C2: configs/resources/audio/normalised_Smbdytolv_mj.wav #AI
          C3: configs/resources/audio/normalised_Smbdytolv_audit.wav #human
          C4: configs/resources/audio/normalised_Smbdytolv_CD.wav #AI
          C5: configs/resources/audio/normalised_Smbdytolv_r.wav #human
    

    - type: mushra
      id: english_test_2
      name: English test 2
      content: 
      showWaveform: false
      enableLooping: false 
      reference: configs/resources/audio/normalised_1min_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/normalised_Eng_suno.wav #AI
          C2: configs/resources/audio/normalised_Callmyname.wav #human
          C3: configs/resources/audio/normalised_1min_suno.wav #AI
          C4: configs/resources/audio/normalised_Eyes_SUNO.wav #AI
          

    - type: mushra
      id: japanese_test_1
      name: Japanese test 1
      content: 
      showWaveform: false
      enableLooping: false 
      #sliderCount: 2 
      reference: configs/resources/audio/normalised_39_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/normalised_39_AI_kim.wav #AI
          C2: configs/resources/audio/normalised_39_AI_ace.wav #AI
          C3: configs/resources/audio/normalised_39_39.wav #AI
          C4: configs/resources/audio/normalised_39_VT.wav #human

    

    - type: mushra
      id: japanese_test_2
      name: Japanese test 2
      content: 
      showWaveform: false
      enableLooping: false 
      reference: configs/resources/audio/normalised_Utawaku.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/normalised_JP_suno.wav #AI
          C2: configs/resources/audio/normalised_39_suno.wav #AI
          C3: configs/resources/audio/normalised_Choco.wav #human
          C4: configs/resources/audio/normalised_VoisonaUI.wav #AI
          C5: configs/resources/audio/normalised_KAFU1.1.wav #AI

    
  

    - type: mushra
      id: mandarin_test_1
      name: Mandarin test 1
      content: 
      showWaveform: false
      enableLooping: false 
      sliderCount: 2 
      reference: configs/resources/audio/normalised_TianHou_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/normalised_TianHou_justin.wav #AI
          C2: configs/resources/audio/normalised_TianHou_boi.wav #human
          C3: configs/resources/audio/normalised_TianHou_xzhq.wav #human
          C4: configs/resources/audio/normalised_TianHou_david.wav #AI

    

    - type: mushra
      id: mandarin_test_2
      name: Mandarin test 2
      content: 
      showWaveform: false
      enableLooping: false 
      reference: configs/resources/audio/normalised_IN_K.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/normalised_Mandarin_suno.wav #AI
          C2: configs/resources/audio/normalised_ManIndie2.wav #human
          C3: configs/resources/audio/normalised_Man_suno2.wav #AI
          C4: configs/resources/audio/normalised_ManIndie3.wav #human
 
    - type: mushra
      id: cantonese_test_1
      name: Cantonese test 1
      content: 
      showWaveform: false
      enableLooping: false 
      sliderCount: 2 
      reference: configs/resources/audio/normalised_1_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/normalised_1_AImodel.wav #AI
          C2: configs/resources/audio/normalised_1_WanK.wav #human
          C3: configs/resources/audio/normalised_1_cover1.wav #human
          C4: configs/resources/audio/normalised_1_cover2.wav #human
          C5: configs/resources/audio/normalised_1_cm.wav #human
    

    - type: mushra
      id: cantonese_test_2
      name: Cantonese test 2
      content: 
      showWaveform: false
      enableLooping: false 
      reference: configs/resources/audio/normalised_CantoIndie.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/normalised_Suno_CantoRap.wav #AI
          C2: configs/resources/audio/normalised_CantoRap.wav #human
          C3: configs/resources/audio/normalised_Suno_CantoPop.wav #AI
          C4: configs/resources/audio/normalised_CantoIndie2.wav #human

    


    - type: finish
      name: Thank you
      content: Thank you for attending
      popupContent: Your results were sent. Goodbye and have a nice day
      showResults: true
      writeResults: true
