# test config mushra page, no waveform, 3 conditions, no looping


testname: MUSHRA without looping and waveform
testId: mushra_noloop_nowav
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:

    - type: consent
      content: "This is a MUSHRA listening test aiming to investigate on participants perception and ability to identify AI singers. You may choose not to answer any questions or exit the test at anytime."

    - type: languageFamiliarity
      id: lang_fam
      name: Language Familiarity
      content: "Please rate your familiarity with the following languages (0 = not familiar, 100 = very familiar)."
    

    - type: mushra
      id: trial2
      name: MUSHRA test 
      content: test description
      showWaveform: false
      enableLooping: false 
      sliderCount: 2 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav

    

    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: false
      enableLooping: false 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav

    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: false
      enableLooping: false 
      sliderCount: 2 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav

    

    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: false
      enableLooping: false 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav

    - type: languageFamiliarity
      id: lang_fam
      name: Language Familiarity
      content: "Please rate your familiarity with the following languages (0 = not familiar, 100 = very familiar)."
    

    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: false
      enableLooping: false 
      sliderCount: 2 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav

    

    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: false
      enableLooping: false 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav

    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: false
      enableLooping: false 
      sliderCount: 2 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav

    

    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: false
      enableLooping: false 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav

    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: false
      enableLooping: false 
      sliderCount: 2 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav

    

    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: false
      enableLooping: false 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav


    - type: finish
      name: Thank you
      content: Thank you for attending
      popupContent: Your results were sent. Goodbye and have a nice day
      showResults: true
      writeResults: true
